version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: ./api
    container_name: laravel_api
    restart: always
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laraveluser
      DB_PASSWORD: laravelpassword
    depends_on:
      - db
    ports:
      - "9000:9000"

  client:
    build:
      context: ./client
    container_name: nuxt_client
    restart: always
    environment:
      API_URL: http://api:9000
    depends_on:
      - api
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs/nginx-selfsigned.crt:/etc/nginx/certs/nginx-selfsigned.crt
      - ./nginx/certs/nginx-selfsigned.key:/etc/nginx/certs/nginx-selfsigned.key
    depends_on:
      - client
      - api

volumes:
  db_data:
