version: '3.8'  # Docker Compose version

services:
  db:  # MySQL service
    image: mysql:8.0  # MySQL version
    container_name: mysql
    restart: always
    environment:  # MySQL configuration
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
    ports:
      - "3306:3306"  # Expose MySQL port
    volumes:
      - db_data:/var/lib/mysql  # Persistent storage

  api:  # Laravel API service
    build:
      context: ./api  # Build context
    container_name: laravel_api
    restart: always
    environment:  # API database configuration
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laraveluser
      DB_PASSWORD: laravelpassword
    depends_on:
      - db  # Wait for db service
    ports:
      - "9000:9000"  # Expose API port

  client:  # Nuxt.js client service
    build:
      context: ./client  # Build context
    container_name: nuxt_client
    restart: always
    environment:
      API_URL: http://api:9000  # API URL for client
    depends_on:
      - api  # Wait for API service
    ports:
      - "3000:3000"  # Expose client port

  nginx:  # Nginx web server
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"  # HTTP
      - "443:443"  # HTTPS
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Nginx configuration
      - ./nginx/certs/nginx-selfsigned.crt:/etc/nginx/certs/nginx-selfsigned.crt  # SSL certificate
      - ./nginx/certs/nginx-selfsigned.key:/etc/nginx/certs/nginx-selfsigned.key  # SSL certificate key
    depends_on:
      - client  # Wait for client
      - api  # Wait for API

volumes:
  db_data:  # Persistent volume for MySQL data
